/**
 * Build-time script that generates js/config.js from environment variables.
 * Vercel runs this via the "build" npm script before serving the static site.
 *
 * Set API_BASE_URL in Vercel → Settings → Environment Variables.
 * Falls back to http://localhost:5000 for local development.
 */
const fs = require("fs");
const path = require("path");

const API_BASE_URL = process.env.API_BASE_URL || "http://localhost:5000";

const configContent = `/**
 * Auto-generated by scripts/generate-config.js — do not edit manually.
 * To change the API URL, set the API_BASE_URL environment variable.
 */
window.API_BASE_URL = "${API_BASE_URL}";
`;

const outPath = path.join(__dirname, "..", "js", "config.js");
fs.writeFileSync(outPath, configContent, "utf-8");

console.log(`✅ js/config.js generated with API_BASE_URL = "${API_BASE_URL}"`);
